-- MySQL Script generated by MySQL Workbench
-- Sat Apr  6 22:48:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `iddepartamentos` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`iddepartamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`municipio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(45) NULL,
  `departamentos_iddepartamentos` INT NULL,
  PRIMARY KEY (`idmunicipio`),
  CONSTRAINT `fk_municipio_departamentos`
    FOREIGN KEY (`departamentos_iddepartamentos`)
    REFERENCES `mydb`.`departamentos` (`iddepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_municipio_departamentos_idx` ON `mydb`.`municipio` (`departamentos_iddepartamentos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `idpersonas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `correo` VARCHAR(45) NULL,
  `iddepartamentos` INT NULL,
  `idmunicipio` INT NULL,
  PRIMARY KEY (`idpersonas`),
  CONSTRAINT `fk_personas_departamentos1`
    FOREIGN KEY (`iddepartamentos`)
    REFERENCES `mydb`.`departamentos` (`iddepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_municipio1`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `mydb`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_personas_departamentos1_idx` ON `mydb`.`personas` (`iddepartamentos` ASC) VISIBLE;

CREATE INDEX `fk_personas_municipio1_idx` ON `mydb`.`personas` (`idmunicipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admins` (
  `idadmins` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmins`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
